### ISSUE TITLE
[Feature Request] Disable compilation of map files?

### ISSUE THREAD

**Issue by lonix1** [malvahq/vscode-plugin-dartsass#13]
There is a config option to disable minification: `"dartsass.disableMinifiedFileGeneration": true`.

Is it somehow possible to disable creation of `.map` files? (I looked in the readme but didn't find anything.)

**Comment by akkumar** [comment]
Sorry - right now, none exists. 

I will take this as  a feature request for a property 'disableSourceMapGeneration' . Right now - none exists though. Should be able to get this implemented by early next week though.

**Comment by lonix1** [comment]
Okay I thought maybe I just didn't see it in the docs, again 😆 

`disableSourceMapGeneration` would be a cool feature!

**Comment by akkumar** [comment]
So - a newer release of the plugin 0.0.83 has been rolled out. 

Added a new property - `dartsass.disableSourceMap` to disable source map generation. By default it is false, so that would imply source maps get generated by default  - as before. 

Let me know if that works.

**Comment by lonix1** [comment]
Yeah! That works nicely! Thanks 😃
