### ISSUE TITLE
Running the contributed command: 'dartsass.watchDir' failed.

### ISSUE THREAD

**Issue by b3wii** [malvahq/vscode-plugin-dartsass#18]
dart-sass	1.25.0	(Sass Compiler)	[Dart] dart2js	2.7.0	(Dart Compiler)	[Dart]
vs code v1.41.1

**Comment by b3wii** [comment]
Relaunch failed: Watch Not implemented in built-in sass package. Check if sassbinPath is set.

**Comment by akkumar** [comment]
> Check if sassbinPath is set.

So you need to install `sass` binary locally in your machine or in your project.

Say,

`npm install [-g] sass` 

And then, set `sassBinPath` property at workspace level and then restart the watchers . 

It should work then. For more help, refer to README.md. 

Feel free to add here if this does not work.

**Comment by akkumar** [comment]
@b3wii - let me know if the recommendation above works and I can close the issue
