### ISSUE TITLE
Cannot unwatch

### ISSUE THREAD

**Issue by lonix1** [malvahq/vscode-plugin-dartsass#20]
Hey @akkumar 

I'm having trouble related to #12, but I'm opening a new issue because it may be a different issue. My config is exactly as you've described in that issue, but I can't use relative paths anymore, so I went back to using `../../../`.

I was investigating and tried to "unwatch" and "watch" the directory to see if I could fix it, but I can't unwatch - it says
> /home/username/work/src/foo/bar/css not being watched before

Which is strange, because in the debug window it shows that there is a watcher on that directory.

Did something change in the last update maybe? Or is it just me?

**Comment by akkumar** [comment]
This seems like a regression introduced. I am going to have to debug that a
little.

Meanwhile to reset the "watchers" - you can invoke the cmd ">DartSass:
Clear All sass watchers"  and then try to watch the directory again using
the menuitem on the right.

Sorry about the regression while I investigate what is happening.

**Comment by akkumar** [comment]
> but I can't use relative paths anymore, so I went back to using ../../../.

Can you help share what the `watchDirectories` option read in your project config ?

Also - platform - is it linux or windows ?

**Comment by lonix1** [comment]
The project root has `node_modules` and `src` subdirectories, and I start vscode from there.

Config:
````
"dartsass.disableMinifiedFileGeneration": true,
"dartsass.disableSourceMap": true,
"dartsass.pauseInterval": 2,
"dartsass.sassBinPath": "node_modules/.bin/sass",
"dartsass.includePath": ["node_modules"],
"dartsass.watchDirectories": [
  "src/foo/bar/css"
],
````

**Comment by akkumar** [comment]
Curious , if `watchDirectories` was edited manually ? 

You can "> DartSass: Clear All Sass  Watchers" and then watch the directory again using the menuitem " DartSass: Watch Directory" that appears in the context menu for every folder on the left hand side explorer. 

Let me know if following above fixes the issue though.

[ `watchDirectories` was meant to be a stop gap persistence store internally used by the plugin to help restart watchers, as opposed to be directly manipulated by the user.

I understand it was a bad design to have used configuration api for internal persistence used by the plugin. I am working on [some alternative](https://stackoverflow.com/questions/51821924/how-to-persist-information-for-a-vscode-extension) meanwhile though. 
 ].

**Comment by lonix1** [comment]
I deleted that entry, used the command "Clear all sass watchers", then started watching the appropriate directory, and the plugin recreated the correct (absolute) path for `dartsass.watchDirectories`.

That means I can start/stop watchers properly. I guess it was edited manually for some reason, not sure why. It was working though, just couldn't be stopped.

So I think this is not an issue after all - that config option must not be edited by hand! Thanks for the explanation.

---

That memento API looks interesting. Looks like you can store anything you want and it survives. I wouldn't waste time on it though - the docs say
> There is no need to set this property manually in the workspace

...which is good enough! 😄

**Comment by lonix1** [comment]
About the original problem with relative imports instead of `../../../../etc` - I assume that is still working, so the problem is just me?
