### ISSUE TITLE
regression of include path issue introduced again 

### ISSUE THREAD

**Issue by akkumar** [malvahq/vscode-plugin-dartsass#22]
Due to a bunch of recent fixes , regression of #12 has come up again. 

tracking the issue.

**Comment by akkumar** [comment]
> I was wondering, does this still work for you? ...If so then it's just me.

Nope. not working for me either. Checking what is happening now.

**Comment by akkumar** [comment]
Release v0.4.1 should have the fix for this regression. 

There was an earlier bug (#16) during which an issue related to spaces in includePath was reported and the fix introduced this regression. 

Sorry about that . 

@lonix1 - you can get the latest release and see if that helps fixes the given issue. sorry about the regression here.

**Comment by lonix1** [comment]
Hey @akkumar
Thanks! The latest update fixes it - you are the man! 👍

**Comment by akkumar** [comment]
thanks. apparently the fix is not to have "spaces" in includePath at all. If there are "spaces" in includePath then things go south quickly and silently. 

not much of an issue with linux but more of an issue with windows though. 

all these quirks with cmd line is because dart-sass does not expose a js api to set a watcher. hopefully when that happens  we might get away from these quirks.

**Comment by lonix1** [comment]
`'Program Files/Why does this not work/src'` ...oops 😄
