### ISSUE TITLE
windows implementation launches a new window for every sass watcher

### ISSUE THREAD

**Issue by akkumar** [malvahq/vscode-plugin-dartsass#24]
windows implementation launches a new window for every sass watcher. 

it seems like it is based on how sass.cmd is implemented but for now - tracking it here as an issue. 

Based on discussion from #16 . 

> Think I found the issue of windows showing on child_process and it looks like a node bug [here](https://github.com/nodejs/node/issues/21825).

- courtesy: @ImSeaWorld

**Comment by akkumar** [comment]
Logged an issue with [dart-sass#954 ](https://github.com/sass/dart-sass/issues/954) to get their suggestions

**Comment by ImSeaWorld** [comment]
Actually looked into this and would like for you to give it a try. For windows users, use ``node.exe`` for the executable and ``./node_modules/sass/sass.js`` for the bin.

```javascript
var spawn = require('child_process').spawn,child;

child = spawn('node.exe', 
    [ 
        'd:\\vsc-dartsass-issue-16\\node_modules\\sass\\sass.js',
        '-I', 'd:\\vsc-dartsass-issue-16\\src\\scss', '--watch', 'd:\\vsc-dartsass-issue-16\\src\\scss:d:\\vsc-dartsass-issue-16\\public'
    ],

    {
        detached:true, 
        shell: false, 
        windowsHide: true
    }
);

child.stdout.on('data', (chunk)=> {
    console.log(`Data out: ${chunk.toString()}`);
});

child.stderr.on('data', (chunk)=> {
    console.log(`Error out: ${chunk.toString()}`);
});

child.on('exit', ()=> {
    console.log('Finished');
});

child.stdin.end();
```

By doing it this way, we'll get the correct behavior on windows.

**Comment by akkumar** [comment]
Thanks @ImSeaWorld for the debugging. 

I had incorporated the changes in 0.5.0+ . 

Let me know what you see and if this still works. 

If not - feel free to add what you see in the logs ( preferably with the "dartsass.debug" set to true ).

**Comment by akkumar** [comment]
>         'd:\\vsc-dartsass-issue-16\\node_modules\\sass\\sass.js',

Also you should set your `sassBinPath` to `node_modules\\sass\\sass.js`   ( as opposed to sass.cmd ) for this to work.

**Comment by akkumar** [comment]
@ImSeaWorld - can you help verify if the implementation above works ?

**Comment by lekoala** [comment]
@akkumar for me, no console windows anymore :)

**Comment by akkumar** [comment]
Thanks @lekoala  for helping confirming this. 

@ImSeaWorld - thanks for your help with the fix.

**Comment by akkumar** [comment]
FYI . A new property `nodeExePath` also added as a config property ( just in case, the default node.exe does not work for the user. Say - they have upgraded node or trying a new version of node etc. ).
