### ISSUE TITLE
autoprefixer support and watch changes?

### ISSUE THREAD

**Issue by lekoala** [malvahq/vscode-plugin-dartsass#3]
hi again,

two small other things that would make using your extension perfect for my use case:
- would it be possible to enable autoprefixer support for compiled css? i'm not using any build step (and rely on the extension to build my css files) and really this remove one extra step for me :-)
as a reference, this plugin does it : https://github.com/yutent/scss-to-css
- would there be a way to watch changes from imported files somehow? i'd love to have my main scss file compiled when i update one of the imports?

**Comment by akkumar** [comment]
1) Autoprefixer seems interesting. Let me give it a spin soon. 

2) This sort of implies building the dependency tree among the files in a given project. I am going to have to dig a bit around looking into the vscode api and language server before getting to it. I have logged a separate issue #4 to track the same.

**Comment by akkumar** [comment]
Release v0.0.64 should contain the changes. 

[ From changelog ] 
* Introduce a property disableAutoPrefixer to disable postcss processing using autoprefixer library.
* Introduce a property autoPrefixBrowsersList: Default: [ "last 2 version"]. List of browsers to be specified for autoprefixer. See https://github.com/browserslist/browserslist#readme for more details

**Comment by lekoala** [comment]
hey @akkumar that is great, your extension is quickly becoming my favorite extension for compiling sass :-)

**Comment by akkumar** [comment]
@lekoala - Good to know the feedback. If you are indeed happy, a few stars for the extension in the [vscode marketplace malvahq.dartsass](https://marketplace.visualstudio.com/items?itemName=malvahq.dartsass) would be useful :) :)

**Comment by akkumar** [comment]
@lekoala - let me know if this works for you and if i can go ahead and close this issue.

**Comment by lekoala** [comment]
@akkumar works great and I added a review, it totally deserves it!
