### ISSUE TITLE
target dir

### ISSUE THREAD

**Issue by lekoala** [malvahq/vscode-plugin-dartsass#5]
Hi again,

I have often the following structure:

- css
- images
- sass
- scripts etc

ideally, sass files would be compiled into the css folder for a clear separation

any way to specify a target dir? either with a comment in the file or some kind of workspace settings?

**Comment by akkumar** [comment]
As it stands today, no. But if we were to implement say `targetDir` (or similar), I am thinking of the following:

* It probably should not exist before ( to prevent overwriting by mistake )
* It should not be in source control either.
*  And, in case of nested directories, `targetDir` should mirror the directory structure of source directory structure as well ( In the case you had mentioned above, that would be `sass` ). 

I am trying to think what would be the best way of formulating this to the user so they get to customize it better.  The 3rd point above is a bit tricky - so probably we need to ask both the sourc and the target directory ( to better mirror  )  ? 

Let me know what you would like to see as properties so it can be customizable as per the user.

**Comment by lekoala** [comment]
maybe we could leverage the package.json file in the project root and specify some custom vendor property like

```
{
"dartsass": {
  "targetDir":"../css"
}
}
```

indeed it would totally make sense to mirror the folder structure
as for overwriting, i don't think it's a big issue : if you specify a targetDir, you know what you do. if you don't, you have source control. it's not like you are going to write into folders outside of your projects or anything

**Comment by akkumar** [comment]
Introduced the following 2 properties. 

* `dartsass.targetDirectory`: Default: Empty. The target directory to write the generated css files. This can be an absolute directory or a directory, relative to project root.
* `dartsass.targetMinifiedDirectory`: Default: Empty. The target directory to write the generated minified css files. This can be an absolute directory or a directory, relative to project root.

For now, the mirroring of directory structure is *not yet* implemented. (It gets interesting when we try to define mirroring. Mirror directory relative to project root ? ) .

Instead it merely writes the generated css (and .min.css) file to the target directory. 

Release 0.0.65 of the plugin should contain this. Let me know if this would help.

**Comment by akkumar** [comment]
@lekoala - let me know if the options mentioned above work for you and if we can go ahead and close it.

**Comment by gacallea** [comment]
@akkumar FWIW the paths work for me. I only set them in the vscode settings.json as I don't have a package file. my 2c.

**Comment by lekoala** [comment]
@akkumar works great, and since i can add this setting at workspace level, it's perfect!
