### ISSUE TITLE
sass bin path

### ISSUE THREAD

**Issue by gacallea** [malvahq/vscode-plugin-dartsass#6]
premise: don't know the inner workings so this may be redundant/unnecessary.

it would be nice to be able to specify the SASS bin. On macOS SASS can be installed with brew (officially supported/suggested by SASS Lang site). I would like to be able to specify the path for the plugin, to /usr/local/bin/sass 

thank you

**Comment by gacallea** [comment]
I tested and it works without setting a path. the correct sass bin is detected.

**Comment by akkumar** [comment]
Thanks, @gacallea . 

The plugin comes built-in with sass compiler and uses the same to compile the sass. 

As it stands today, it does not take into account any external sass binary when it comes to compiling. 
What you have seen is the output of the built-in sass library as opposed to any external binary. 

I think such a flexibility ( to specify a path to binary) would be a good thing though. So I am reopening this for now.

**Comment by akkumar** [comment]
New release (checkout 0.0.71 or after) contains the following property. 

* `dartsass.sassBinPath`: Default: Empty.

  Eg: `/usr/local/bin/sass` PATH of sass binary to be used to compile , as opposed to the sass compiler that comes built-in with the plugin. `Beta` support only.

**Comment by gacallea** [comment]
@akkumar thank you so much. you rock.

**Comment by akkumar** [comment]
@gacallea - Great. Feel free to test this option and if you are happy feel free to close this issue then. 

Do let me know if you face issues if any.

**Comment by gacallea** [comment]
@akkumar I've set the path and it works fine. it also generates the map files now.
