### ISSUE TITLE
plugin does not load with webpack --mode production

### ISSUE THREAD

**Issue by akkumar** [malvahq/vscode-plugin-dartsass#7]
Packing with `webpack --mode production` fails to activate the plugin at all. 

`cannot read property call of undefined` is what we get when we try to debug the plugin. 

`
        "webpack": "4.41.1",
        "webpack-cli": "3.3.9",
`

Ironically , packing using `webpack --mode development` seems to work.

**Comment by gacallea** [comment]
@akkumar the plugin works now but it won't generate minified versions.

**Comment by gacallea** [comment]
@akkumar my bad. minimized version also need a path. ignore my previous comments. it works.

**Comment by akkumar** [comment]
@gacallea - you were right to expect the target directory of minified versions to be set to target of normal css directory initially. I had since then fixed the same. 

Of course, for those who need it, the option to override target for minified versions still exists as before.

v0.0.68  and above should contain those changes. FYI . 

Meanwhile. If you are happy, a few stars for the extension in the [vscode marketplace malvahq.dartsass](https://marketplace.visualstudio.com/items?itemName=malvahq.dartsass) would be useful :) :)

**Comment by akkumar** [comment]
With the latest webpack       `  "webpack": "4.41.2",` - the issue seems to have been fixed. Trying production packing from here on.
