### ISSUE TITLE
Project-specific target and include paths

### ISSUE THREAD

**Issue by crittag** [malvahq/vscode-plugin-dartsass#8]
Hi

Is there any way to set the includePath and targetDirectory properties on an individual project?

I am working with a number of sites where the paths is not identeical and so having to change the paths when I go into each project is a bit of a pain!

Cheers
Greg

**Comment by akkumar** [comment]
So - behind the scenes , this extension uses the `vscode.workspace.getConfiguration` api to retrieve the configuration settings. 

Let me know if there is a way to retrieve project specific settings though, to achieve what you are referring to.

**Comment by akkumar** [comment]
As of now - there is a workspace specific option for target and include directory ( in addition to the user-level properties ) for customization. Let me know if that would work. Closing this for now.
