### ISSUE TITLE
CMD + SHIFT + P is a bad idea on Mac

### ISSUE THREAD

**Issue by gacallea** [malvahq/vscode-plugin-dartsass#9]
@akkumar cmd + shift + p on mac is used to show all commands (default vs code for mac), you should think about another shortcut (entirely or for mac).

keep up the great work!

ps: I already starred 5 stars on the review!

**Comment by akkumar** [comment]
Oops ! Sorry about that.
For now, I have made a new release but removed the kbd shortcuts altogether. 

I am thinking about better combinations  for the kbd shortcut, so any suggestions are welcome. 

But for now - with a later release, the kbd shortcuts should have been removed altogether. 

Thanks for the review and the stars. Keep the feedback coming !

**Comment by gacallea** [comment]
@akkumar you rock :)

if there's one thing I don't like about vs code is that there's no standardized shortcut rules system. many extensions conflict here and there. I wish microsoft would apply a standard for everybody.

**Comment by akkumar** [comment]
@gacallea - for now - can we close this issue if it looks ok ? As discussed earlier , kb shortcuts have been removed entirely and I have no intention of bringing them back again.
